# Generated by Django 3.0.2 on 2020-01-20 10:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.PathAndRename('user_images')),
        ),
    ]
