# Generated by Django 3.0.2 on 2020-01-20 10:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200120_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_images/default.png', upload_to=main.models.PathAndRename('user_images')),
        ),
    ]
