# Generated by Django 2.0 on 2020-02-28 11:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200120_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default.png', upload_to=main.models.PathAndRename('user_images')),
        ),
    ]
