# Generated by Django 3.0.2 on 2020-01-22 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200120_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lat',
            field=models.FloatField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='image',
            name='lng',
            field=models.FloatField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
