# Generated by Django 3.0.2 on 2020-02-19 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imagefile_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='result',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='score',
            field=models.FloatField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
