# Generated by Django 2.0 on 2020-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_imagefile_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
