# Generated by Django 2.0 on 2020-04-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200403_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifier',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='classifier',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to='api.ObjectType'),
        ),
    ]
