# Generated by Django 2.0 on 2020-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200420_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
