# Generated by Django 2.0 on 2020-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200420_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='pipeline_status',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
