# Generated by Django 2.0 on 2020-04-23 06:47

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_imagefile_pipeline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(max_length=200)),
                ('model_format', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=api.models.PathAndRename('image'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
