# Generated by Django 2.0 on 2020-04-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200423_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='offline_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to='api.OfflineModel'),
        ),
    ]
