# Generated by Django 2.0 on 2020-04-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_classifier_offline_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemodel',
            name='offline_model_labels',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
